services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    command: bash -c 'while !</dev/tcp/mysql/3306; do sleep 1; done; npm start'
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
